package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.63

import (
	"context"
	"fmt"

	"github.com/antunesluiz/go-hexagonal-demo/internal/adapters/graphql/generated"
	"github.com/antunesluiz/go-hexagonal-demo/internal/domain/models"
)

// CreatePost is the resolver for the createPost field.
func (r *mutationResolver) CreatePost(ctx context.Context, title string, content string, authorID string) (*models.Post, error) {
	panic(fmt.Errorf("not implemented: CreatePost - createPost"))
}

// Author is the resolver for the author field.
func (r *postResolver) Author(ctx context.Context, obj *models.Post) (*models.User, error) {
	panic(fmt.Errorf("not implemented: Author - author"))
}

// GetPost is the resolver for the getPost field.
func (r *queryResolver) GetPost(ctx context.Context, id string) (*models.Post, error) {
	panic(fmt.Errorf("not implemented: GetPost - getPost"))
}

// Post returns generated.PostResolver implementation.
func (r *Resolver) Post() generated.PostResolver { return &postResolver{r} }

type postResolver struct{ *Resolver }
